services:
  - type: web
    name: diabetes-prediction
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers=1 --threads=4 --timeout=120
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
